### ISSUE TITLE
help with test suite using docker on TravisCI/CircleCI

### ISSUE THREAD

**Issue by thomasleveil** [thomasleveil/nginx-proxy#2]
I'm struggling making the [bats test suite](https://github.com/thomasleveil/nginx-proxy/tree/test-suite/test) succeed on [CircleCI](https://circleci.com/gh/thomasleveil/nginx-proxy) or [TravisCI](https://travis-ci.org/thomasleveil/nginx-proxy) while it runs fine on my computer (Windows▶Vagrant▶Ubuntu▶docker 1.8.1)

On the Travis side, things seems very random. Maybe due to how they set up the docker daemon?

On the CircleCI site, things are better and more consistent, but test [`5 [docker] separated containers (nginx + docker-gen + nginx.tmpl)`](https://github.com/thomasleveil/nginx-proxy/blob/test-suite/test/docker.bats#L68) won't ever pass (while it passes at home).

I'm out of idea. Maybe I left out something stupid.... any help is appreciated. @md5 ?

**Comment by thomasleveil** [comment]
for Travis, maybe running our containers in a [DinD container](https://hub.docker.com/r/tianon/dind/) (or [this one](https://hub.docker.com/r/dockerswarm/dind/)) would help.

![docker-meme](https://cloud.githubusercontent.com/assets/42300/9866007/7a819830-5b5d-11e5-9b99-21bfc585ea2a.jpg)

**Comment by md5** [comment]
For the Circle CI failure, I'd try logging `$status` to see what the exit code from `curl` was. That may help determine why the "after" request is not shown in the Nginx logs and why it's returning empty output.

For the Travis failure, it looks like exit code 123 from `xargs` means that the underlying command failed with exit code 1-125, so that won't help determine what's happening with the `docker rm` command (although it does let us know that `docker ps` returned a non-empty value, else the `xargs -r` would have returned exit code 0).

After I tweaked the `teardown` function a bit, I managed to get this output:

```
# Error response from daemon: Cannot destroy container 8ac9e366f78e: Could not kill running container, cannot remove - [8] System error: permission denied
# Error response from daemon: Cannot destroy container ad33b147088e: Could not kill running container, cannot remove - [8] System error: permission denied
# Error response from daemon: Cannot destroy container 25d0f9c7f139: Could not kill running container, cannot remove - [8] System error: permission denied
# Error response from daemon: Cannot destroy container 71529aeeec6e: Could not kill running container, cannot remove - [8] System error: permission denied
# Error response from daemon: Cannot destroy container 0b6f3c5064ae: Could not kill running container, cannot remove - [8] System error: permission denied
# Error: failed to remove containers: [8ac9e366f78e ad33b147088e 25d0f9c7f139 71529aeeec6e 0b6f3c5064ae]
```

I tried a few things to try to get the Docker daemon to tell me why it's getting an `EPERM` error, but I didn't make any headway. You can see the last build I tried here: https://travis-ci.org/appropriate/nginx-proxy/builds/80374017

It looks like the `[8]` in that output may indicate an `ENOEXEC`, but I couldn't quite figure out how that exact error message could be generated. Google only showed me one case where that exact error message occurred and it was in this Pastebin: http://pastebin.com/f2MkJE3H

Unfortunately, I couldn't find any references to that Pastebin, so I'm not sure if anyone ever figured out what's going on there.

**Comment by md5** [comment]
Pinging @thaJeztah in case he can recommend someone on the Docker team who might be able to better understand what the nature of the Travis failure is.

**Comment by thomasleveil** [comment]
some related stuff:
- https://github.com/travis-ci/travis-ci/issues/4661
- https://github.com/docker/docker/issues/15101#issuecomment-128712142
- https://github.com/docker/docker-py/pull/743
- [here](https://github.com/travis-ci/travis-ci/issues/4661#issuecomment-135537118) it is also suggestied to try DinD

to try:
- [x] use `kill -9` on the container PID before `docker rm`
- [x] `sudo rm /etc/apparmor.d/docker && sudo service apparmor reload`

**Comment by thaJeztah** [comment]
Hm, not too familiar with the way the Docker Travis is setup, I do know the dind script used by Docker was recently changed, because as of Docker 1.8, most of the hacks are no longer needed (https://github.com/docker/docker/pull/15596).

@jfrazelle is the person making all magic happen related to Jenkins (and, previously CircleCi) in the Docker project :smile:

**Comment by md5** [comment]
Thanks @thaJeztah

**Comment by md5** [comment]
I just managed to figure out that the "[8]" in the error message refers to the numeric id of the `SystemError` value from [`libcontainer.ErrorCode`](https://godoc.org/github.com/docker/libcontainer#ErrorCode), not to `ENOEXEC`. Somehow I wasn't able to track that down in my late-night perusal of the code last night.

**Comment by thomasleveil** [comment]
@md5 is there any way to get more details about what kind of system error?

Also, I tried and failed with the `kill -9` and `apparmor` tricks :/ I will move on with dind

**Comment by thomasleveil** [comment]
TravisCI won't detect my new commits... [traviscistatus.com](https://www.traviscistatus.com/) is all :white_check_mark: 

I might have reached some kind of abuse level :no_mouth:

**Comment by md5** [comment]
It looks like the "permission denied" error message indicate `EACCES` or `EPERM`: https://github.com/golang/go/blob/f9ed2f75c43cb8745a1593ec3e4208c46419216a/src/os/error_unix.go#L35

I was thinking about `strace`-ing the Docker daemon process to see wtf it's trying to do, but I was also have trouble with Travis earlier. I also need to refine an attempt I made to check the audit logs after the failure occurs, but I won't have time until later this evening or possibly tomorrow or Thursday.

Trying out `dind` sounds OK as a stop-gap measure, but I think longer term this needs to be fixed by the Travis folks (or the Docker folks if there's a Docker bug here).

**Comment by thomasleveil** [comment]
I'm starting to lose control over my modest contribution to nginx-proxy :scream_cat:
Thanks again for the support!

oh and it seems TravisCI was under DDOS earlier this day

**Comment by thaJeztah** [comment]
Oh, possible good reading material; https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by thomasleveil** [comment]
Thank you @thaJeztah, this has been a useful reading

**Comment by thomasleveil** [comment]
@md5 just to let you know I gave up on Travis and succeeded in making this work on CircleCI, see https://github.com/jwilder/nginx-proxy/pull/246
